name: "Publish package"

on:
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false # enqueue deployment jobs

env:
  SLACK_DEPLOY_BOT_TOKEN: ${{ secrets.SLACK_DEPLOY_BOT_TOKEN }}
  SLACK_DEPLOY_CHANNEL: ${{ vars.SLACK_DEPLOY_CHANNEL }}
  SLACK_DEPLOY_ERROR_REACTION: ${{ vars.SLACK_DEPLOY_ERROR_REACTION_PRODUCTION }}

jobs:
  start:
    runs-on: ubuntu-latest
    outputs:
      thread_ts: ${{ steps.slack.outputs.ts }}
      version: ${{ steps.version.outputs.value }}
    steps:
      - name: Post to Slack
        uses: Fieldguide/action-slack-deploy-pipeline@v2
        id: slack

      - name: Parse version
        id: version
        run: echo "value=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT

  publish-npm:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Update npm package version for build / publishing
        run: pnpm version ${{ needs.start.outputs.version }} --no-git-tag-version

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          scope: "@fieldguide"

      - name: Install dependencies
        run: pnpm install

      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    needs: start
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Update npm package version for build / publishing
        run: pnpm version ${{ needs.start.outputs.version }} --no-git-tag-version

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish:
    needs:
      - start
      - publish-npm
      - publish-github
    runs-on: ubuntu-latest
    steps:
      - name: "Post to Slack"
        uses: Fieldguide/action-slack-deploy-pipeline@v2
        if: always()
        with:
          thread_ts: ${{ needs.start.outputs.thread_ts }}
          conclusion: true
